# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:10.15.3
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run: cd functions && npm install

      - run:
          name: Build
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                npm run build:production
              fi
              if [ $CIRCLE_BRANCH = 'staging' ]; then
                npm run build:staging
              fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Firebase deploy
          command: node scripts/deploy.js --branch $CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - staging
                - master

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - master
